jobs:
  include:
    - stage: build-image
      script:
        - echo $TRAVIS_BUILD_NUMBER > version.txt
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t $DOCKER_USER/py-build-tools-docker .

      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag $DOCKER_USER/py-build-tools-docker $DOCKER_USER/py-build-tools-docker:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USER/py-build-tools-docker:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USER/py-build-tools-docker:latest
        - curl -XPOST https://hooks.microbadger.com/images/gbnk0/py-build-tools-docker/_WZPSkqhhy137pspxCtRGxofefI=
branches:
  only:
    - master
